import { NextResponse } from 'next/server';
import prisma from '@/lib/db';

export async function POST(request: Request) {
    try {
        const data = await request.json();
        const {
            clientId,
            freelancerId,
            serviceId,
            scheduledAt,
            duration,
            totalPrice,
            status,
            paymentStatus,
            paymentMethod,
            location,
            notes,
            customSport,
            customCategoryId
        } = data;

        if (!clientId || !serviceId || !scheduledAt || !duration || !totalPrice) {
            return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
        }

        // Attempt to get client and service coordinates for the booking
        const client = await prisma.user.findUnique({ where: { id: clientId } });

        let finalServiceId = serviceId;
        let service = null;

        if (serviceId === 'custom') {
            // Get or create a default category for custom packages if none selected
            let catId = customCategoryId;

            if (!catId) {
                const existingCat = await prisma.category.findFirst({
                    where: { name: 'Admin Custom' }
                });
                if (existingCat) {
                    catId = existingCat.id;
                } else {
                    const newCat = await prisma.category.create({
                        data: {
                            name: 'Admin Custom',
                            slug: 'admin-custom-' + Date.now(),
                            description: 'Custom services generated by Admin'
                        }
                    });
                    catId = newCat.id;
                }
            }

            service = await prisma.service.create({
                data: {
                    title: 'Custom Package',
                    description: notes || 'Admin created custom package',
                    price: parseFloat(totalPrice),
                    duration: parseInt(duration),
                    providerId: freelancerId,
                    categoryId: catId,
                    sport: customSport || null,
                    images: '[]',
                    tags: '[]',
                    requirements: '[]',
                    serviceType: 'In-person',
                    location: location || '',
                    coords: '0,0'
                }
            });
            finalServiceId = service.id;
        } else {
            service = await prisma.service.findUnique({ where: { id: serviceId } });
        }


        // Default coords based on what is available
        const coords = location ? "0,0" : (client?.coords || service?.coords || "0,0");

        // Start a transaction as we are creating a booking and potentially other records (like transactions)
        const result = await prisma.$transaction(async (tx: any) => {
            // Create the booking
            const booking = await tx.booking.create({
                data: {
                    clientId,
                    serviceId: finalServiceId,
                    scheduledAt: new Date(scheduledAt),
                    duration: parseInt(duration),
                    totalPrice: parseFloat(totalPrice),
                    status: status || 'PENDING',
                    paymentStatus: paymentStatus || 'PENDING',
                    location: location || service?.location || client?.location || null,
                    coords: coords,
                    notes: notes,
                    // Add default progress if status implies it
                    progress: status === 'COMPLETED' ? 100 : (status === 'IN_PROGRESS' ? 50 : 0),
                }
            });

            // Initialize conversation if none exists
            const existingConvo = await tx.conversation.findFirst({
                where: {
                    clientId: clientId,
                    freelancerId: freelancerId
                }
            });

            if (!existingConvo) {
                await tx.conversation.create({
                    data: {
                        clientId,
                        freelancerId,
                        bookingId: booking.id
                    }
                });
            }

            // If a payment was recorded as COMPLETED, we must ensure it's logged in transactions if required
            // Note: Wallet IDs would typically be pulled here and a tx created, but for a manual connection
            // logging it minimally is fine unless the admin explicitly needs wallet deduction. 
            // For simplicity, we just mark the paymentStatus on the booking.

            return booking;
        });

        // Log the manual connection (generic admin ID for now, as middleware handles auth)
        await prisma.adminLog.create({
            data: {
                adminId: 'system', // Replace with actual decoded admin ID if needed from request headers
                adminEmail: 'system@bails.in',
                action: 'CREATED',
                resource: 'BOOKING',
                resourceId: result.id,
                details: `Connected client ${clientId} with service ${serviceId} (freelancer: ${freelancerId})`,
            },
        });

        return NextResponse.json(result);
    } catch (error) {
        console.error('Error connecting users:', error);
        return NextResponse.json(
            { error: 'Failed to connect users and create booking' },
            { status: 500 }
        );
    }
}
